transcriber:
  language: fr
  hotwords: []
  initial_prompt: ""

  model:
    name: base
    device: cpu
    compute_type: float32

  vad:
    active: true
    threshold: 0.5
    neg_threshold: 0.4
    min_speech_duration_ms: 500
    max_speech_duration_s: 3
    min_silence_duration_ms: 600
    speech_pad_ms: 200

translator:
  language: en
  gemini_model_id: gemini-2.5-flash-lite

condenser:
  padding_ms: 1000

sub_processor:
  spacy_model: fr_dep_news_trf
